"""
Responder.py — Top-level orchestrator for the AI-IDS IPS layer.

This is the integration point between the detection engine and the firewall.
For each alert generated by the engine, the responder:

  1. Asks the policy engine what to do
  2. Executes the decision via the firewall wrapper
  3. Schedules automatic unblock after the configured duration
  4. Logs the action for audit and dashboard display

The responder runs in the same process as the detection engine. It does not
require a separate daemon — unblock scheduling uses an internal timer thread.
"""

import threading
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, List, Dict

from .firewall import Firewall
from .policy import ResponsePolicy, ResponseAction

logger = logging.getLogger("ips.responder")


class Responder:
    """
    The IPS orchestrator.

    Usage
    -----
    >>> from src.prevention import Responder, ResponsePolicy, Firewall
    >>> fw = Firewall(dry_run=False, audit_log=Path("logs/audit.jsonl"))
    >>> policy = ResponsePolicy()
    >>> policy.load_whitelist("config/whitelist.txt")
    >>> responder = Responder(firewall=fw, policy=policy)
    >>>
    >>> # In the detection engine, after generating an alert:
    >>> responder.handle_alert(alert)
    """

    def __init__(
        self,
        firewall: Firewall,
        policy: ResponsePolicy,
        enabled: bool = True,
    ):
        self.firewall = firewall
        self.policy = policy
        self.enabled = enabled

        # Track active blocks for automatic unblock
        self._active_blocks: Dict[str, datetime] = {}  # ip -> expiry
        self._lock = threading.Lock()

        # Start the unblock daemon thread
        self._stop_event = threading.Event()
        self._unblock_thread = threading.Thread(
            target=self._unblock_loop,
            daemon=True,
            name="ips-unblock-daemon"
        )
        self._unblock_thread.start()

    # ── Public API ────────────────────────────────────────────────────────

    def handle_alert(self, alert: dict) -> ResponseAction:
        """
        Process an alert through the policy engine and execute the decision.

        Returns the ResponseAction taken (useful for logging and dashboard).
        """
        if not self.enabled:
            return ResponseAction(
                action="IGNORE",
                duration_sec=0,
                reason="IPS disabled"
            )

        decision = self.policy.decide(alert)
        src_ip = alert.get("src_ip")

        if decision.action == "BLOCK":
            success = self.firewall.block(src_ip, decision.reason)
            if success and decision.duration_sec > 0:
                expiry = datetime.utcnow() + timedelta(seconds=decision.duration_sec)
                with self._lock:
                    self._active_blocks[src_ip] = expiry
                logger.info(
                    f"Scheduled unblock for {src_ip} at "
                    f"{expiry.isoformat()}Z ({decision.duration_sec}s)"
                )

        elif decision.action == "ESCALATE":
            logger.info(f"Escalation pending for {alert.get('src_ip')}: {decision.reason}")

        elif decision.action == "LOG_ONLY":
            logger.debug(f"Log-only alert: {decision.reason}")

        elif decision.action == "IGNORE":
            logger.debug(f"Ignored alert: {decision.reason}")

        return decision

    def active_blocks(self) -> List[Dict]:
        """
        Return a list of currently active blocks for the dashboard.

        Each entry contains: ip, expires_at, seconds_remaining.
        """
        now = datetime.utcnow()
        with self._lock:
            result = []
            for ip, expiry in self._active_blocks.items():
                remaining = max(0, int((expiry - now).total_seconds()))
                result.append({
                    "ip": ip,
                    "expires_at": expiry.isoformat() + "Z",
                    "seconds_remaining": remaining,
                })
        return result

    def shutdown(self) -> None:
        """Stop the unblock daemon. Call before program exit."""
        self._stop_event.set()
        self._unblock_thread.join(timeout=2.0)

    # ── Internal: unblock daemon ──────────────────────────────────────────

    def _unblock_loop(self) -> None:
        """
        Background loop that checks for expired blocks every 5 seconds and
        removes them from the firewall.
        """
        while not self._stop_event.wait(5.0):
            now = datetime.utcnow()
            expired = []

            with self._lock:
                for ip, expiry in self._active_blocks.items():
                    if now >= expiry:
                        expired.append(ip)

                for ip in expired:
                    del self._active_blocks[ip]

            for ip in expired:
                self.firewall.unblock(ip, reason="block duration expired")
